"""breeding_log_child_id_nullable_on_delete_set_null

Revision ID: 488d74589dfc
Revises: adb2c761154c
Create Date: 2026-04-26 09:03:46.282911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '488d74589dfc'
down_revision: Union[str, None] = 'adb2c761154c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breeding_log', 'child_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('breeding_log_child_id_fkey', 'breeding_log', type_='foreignkey')
    op.create_foreign_key(None, 'breeding_log', 'muldo_individual', ['child_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_muldo_individual_parent_f', 'muldo_individual', type_='foreignkey')
    op.drop_constraint('fk_muldo_individual_parent_m', 'muldo_individual', type_='foreignkey')
    op.create_foreign_key('fk_muldo_individual_parent_f', 'muldo_individual', 'muldo_individual', ['parent_f_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_muldo_individual_parent_m', 'muldo_individual', 'muldo_individual', ['parent_m_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_muldo_individual_parent_m', 'muldo_individual', type_='foreignkey')
    op.drop_constraint('fk_muldo_individual_parent_f', 'muldo_individual', type_='foreignkey')
    op.create_foreign_key('fk_muldo_individual_parent_m', 'muldo_individual', 'muldo_individual', ['parent_m_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_muldo_individual_parent_f', 'muldo_individual', 'muldo_individual', ['parent_f_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'breeding_log', type_='foreignkey')
    op.create_foreign_key('breeding_log_child_id_fkey', 'breeding_log', 'muldo_individual', ['child_id'], ['id'])
    op.alter_column('breeding_log', 'child_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
