"""add_progression_snapshot

Revision ID: 78a7b8afe003
Revises: d1e2f3a4b5c6
Create Date: 2026-04-28 16:32:08.395399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78a7b8afe003'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('species_ok_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progression_snapshot')
    # ### end Alembic commands ###
