"""initial_schema

Revision ID: ed2f084bbceb
Revises: 
Create Date: 2026-04-24 16:20:18.552672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed2f084bbceb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muldo_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('breeding_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_species_id', sa.Integer(), nullable=False),
    sa.Column('parent_f_species_id', sa.Integer(), nullable=False),
    sa.Column('parent_m_species_id', sa.Integer(), nullable=False),
    sa.Column('is_optimal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_species_id'], ['muldo_species.id'], ),
    sa.ForeignKeyConstraint(['parent_f_species_id'], ['muldo_species.id'], ),
    sa.ForeignKeyConstraint(['parent_m_species_id'], ['muldo_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muldo_individual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('F', 'M', name='sexenum'), nullable=False),
    sa.Column('is_fertile', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.Enum('captured', 'bred_success', 'bred_fail', 'cloned', name='originenum'), nullable=False),
    sa.Column('parent_f_id', sa.Integer(), nullable=True),
    sa.Column('parent_m_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['muldo_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('breeding_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_f_id', sa.Integer(), nullable=False),
    sa.Column('parent_m_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('target_species_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['muldo_individual.id'], ),
    sa.ForeignKeyConstraint(['parent_f_id'], ['muldo_individual.id'], ),
    sa.ForeignKeyConstraint(['parent_m_id'], ['muldo_individual.id'], ),
    sa.ForeignKeyConstraint(['target_species_id'], ['muldo_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clone_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donor_1_id', sa.Integer(), nullable=False),
    sa.Column('donor_2_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_1_id'], ['muldo_individual.id'], ),
    sa.ForeignKeyConstraint(['donor_2_id'], ['muldo_individual.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['muldo_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_muldo_individual_parent_f', 'muldo_individual', 'muldo_individual', ['parent_f_id'], ['id'])
    op.create_foreign_key('fk_muldo_individual_parent_m', 'muldo_individual', 'muldo_individual', ['parent_m_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE muldo_individual DROP CONSTRAINT IF EXISTS fk_muldo_individual_parent_f')
    op.execute('ALTER TABLE muldo_individual DROP CONSTRAINT IF EXISTS fk_muldo_individual_parent_m')
    op.drop_table('clone_log')
    op.drop_table('breeding_log')
    op.drop_table('muldo_individual')
    op.drop_table('breeding_recipe')
    op.drop_table('muldo_species')
    op.execute('DROP TYPE IF EXISTS sexenum')
    op.execute('DROP TYPE IF EXISTS originenum')
    # ### end Alembic commands ###
